spring:
  application:
    name: batch-server
  profiles:
    active: none
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  cloud:
    config:
      profile: ${PROFILE}

  batch:
    job:
      enabled: false

encrypt:
  key: ${ENCRYPT_KEY}


