spring:
  application:
    name: batch-server
  profiles:
    active: none
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      name: updatePaymentStatusJob

  cloud:
    config:
      profile: ${PROFILE}

encrypt:
  key: ${ENCRYPT_KEY}


